// Modular re-exports for all interfaces
export * from '../interfaces/api.interfaces';
// export * from '../interfaces/paginated.interfaces';
export * from '../interfaces/user.interfaces';
export * from '../interfaces/auth.interfaces';
export * from '../interfaces/role.interfaces';
export * from '../interfaces/project.interfaces';
export * from '../interfaces/task.interfaces';
export * from '../interfaces/dashboard.interfaces';
export * from '../interfaces/dashboard-home.interfaces';
export * from '../interfaces/dashboard-shared.interfaces';
export * from '../interfaces/organization.interfaces';
export * from '../interfaces/branch.interfaces';
export * from '../interfaces/claim.interfaces';
export * from '../interfaces/tenant.interfaces';
export * from '../interfaces/team.interfaces';
export * from '../interfaces/timetracker.interfaces';
export * from '../interfaces/campaign.interfaces';
export * from '../interfaces/enums.interfaces';
// export * from '../interfaces/common.interfaces';
